services:
  db:
    image: postgres:latest
    env_file: database.conf
    ports:
      - 5432:5432
    volumes:
      - data-volume:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
     - .env
    volumes:
      - ./:/app
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      FLASK_ENV: development
      FLASK_APP: ./split/app.py
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    ports:
     - 5000:5000
    restart: always
    depends_on:
      - db
volumes:
  data-volume: